apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: japan-stt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      containers:
        - name: whisper
          image: python:3.10-slim
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
          volumeMounts:
            - name: downloads
              mountPath: /downloads
          stdin: true
          tty: true
      volumes:
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads-pvc
